/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ClienteDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Rodrigo
 */
public class CadastroCliente extends javax.swing.JFrame {
    
    ClienteDAO objClienteDAO = new ClienteDAO();
    /**
     * Creates new form CadastroCliente
     */
    public CadastroCliente() {
        initComponents();
        listarClientes();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeTXT = new javax.swing.JTextField();
        enderecoTXT = new javax.swing.JTextField();
        telefoneTXT = new javax.swing.JTextField();
        salvarBT = new javax.swing.JButton();
        cnpjTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        limparBT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        codigoTXT = new javax.swing.JTextField();
        cpfTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emailTXT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        atualizarBT = new javax.swing.JButton();
        sairBT1 = new javax.swing.JButton();
        alterarBT = new javax.swing.JButton();
        carregarBt1 = new javax.swing.JButton();
        deletarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\17115 (1).png")); // NOI18N
        jLabel1.setText("Clientes");
        jLabel1.setMaximumSize(new java.awt.Dimension(641, 512));
        jLabel1.setMinimumSize(new java.awt.Dimension(641, 512));
        jLabel1.setPreferredSize(new java.awt.Dimension(641, 512));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar novo cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel2.setText("Nome");

        jLabel3.setText("Endereço");

        jLabel4.setText("Telefone");

        enderecoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoTXTActionPerformed(evt);
            }
        });

        salvarBT.setBackground(new java.awt.Color(0, 204, 204));
        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        jLabel5.setText("CPF");

        limparBT.setBackground(new java.awt.Color(0, 204, 204));
        limparBT.setText("Limpar");
        limparBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBTActionPerformed(evt);
            }
        });

        jLabel6.setText("Código");

        codigoTXT.setEnabled(false);

        jLabel7.setText("CNPJ");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel8.setText("(Preencha apenas seu tipo de pessoa.*)");

        jLabel9.setText("Email");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setText("(Ao carregar campos deixe apenas seu tipo de pessoas preenchido.*)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telefoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salvarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limparBT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(enderecoTXT)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cpfTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cnpjTXT))
                    .addComponent(emailTXT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(emailTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(enderecoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpfTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cnpjTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(salvarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(limparBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(telefoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Documento", "Email", "telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);

        atualizarBT.setBackground(new java.awt.Color(0, 204, 204));
        atualizarBT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atualizarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\atualizar.png")); // NOI18N
        atualizarBT.setText("Atualizar");
        atualizarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBTActionPerformed(evt);
            }
        });

        sairBT1.setBackground(new java.awt.Color(0, 204, 204));
        sairBT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sairBT1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\sair.png")); // NOI18N
        sairBT1.setText("Sair");
        sairBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBT1ActionPerformed(evt);
            }
        });

        alterarBT.setBackground(new java.awt.Color(0, 204, 204));
        alterarBT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alterarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\alterar.png")); // NOI18N
        alterarBT.setText("Alterar");
        alterarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarBTActionPerformed(evt);
            }
        });

        carregarBt1.setBackground(new java.awt.Color(0, 204, 204));
        carregarBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carregarBt1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\carregar.png")); // NOI18N
        carregarBt1.setText("Carregar");
        carregarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarBt1ActionPerformed(evt);
            }
        });

        deletarBT.setBackground(new java.awt.Color(0, 204, 204));
        deletarBT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\deletar.png")); // NOI18N
        deletarBT.setText("Deletar");
        deletarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(atualizarBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carregarBt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alterarBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletarBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairBT1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carregarBt1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(atualizarBT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sairBT1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(alterarBT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addComponent(deletarBT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBTActionPerformed
        // TODO add your handling code here:
        listarClientes();
    }//GEN-LAST:event_atualizarBTActionPerformed

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        // TODO add your handling code here:
        try {
            salvar();
        listarClientes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Os campos NAO podem retornar Vazios\n"+e);
        }
        
    }//GEN-LAST:event_salvarBTActionPerformed

    private void sairBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBT1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairBT1ActionPerformed

    private void alterarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarBTActionPerformed
        // TODO add your handling code here:
        try {
            alterarCampos();
            listarClientes();
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Carregue um Registro Primeiro\n"+e);
        }
        
    }//GEN-LAST:event_alterarBTActionPerformed

    private void carregarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarBt1ActionPerformed
        // TODO add your handling code here:
        try {
            CarregarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Clique em um Registro primeiro.\n"+e);
        }      
    }//GEN-LAST:event_carregarBt1ActionPerformed

    private void deletarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBTActionPerformed
        // TODO add your handling code here:
        try {
            deletarCliente();
        listarClientes();
        limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Carregue um Registro Primeiro.\n"+e);
        }          
    }//GEN-LAST:event_deletarBTActionPerformed

    private void enderecoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoTXTActionPerformed

    private void limparBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBTActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_limparBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

        private void limparCampos(){
            nomeTXT.setText("");
            enderecoTXT.setText("");
            telefoneTXT.setText("");
            cpfTXT.setText("");
            cnpjTXT.setText("");
            emailTXT.setText("");
        }
        
        private void CarregarCampos() {
         int setar = tabelaCliente.getSelectedRow();
         codigoTXT.setText(tabelaCliente.getModel().getValueAt(setar, 0).toString());
         nomeTXT.setText(tabelaCliente.getModel().getValueAt(setar, 1).toString());
         cpfTXT.setText(tabelaCliente.getModel().getValueAt(setar, 2).toString());
         cnpjTXT.setText(tabelaCliente.getModel().getValueAt(setar, 2).toString());
         emailTXT.setText(tabelaCliente.getModel().getValueAt(setar, 3).toString());
         telefoneTXT.setText(tabelaCliente.getModel().getValueAt(setar, 4).toString());
         
     }
        private void alterarCampos(){
            int id;
            id = Integer.parseInt(codigoTXT.getText());
            
            Cliente objCliente = new Cliente();
            objCliente.setCodigo(id);
            objCliente.setNome(nomeTXT.getText());
            objCliente.setEmail(emailTXT.getText());
            objCliente.setEndereco(enderecoTXT.getText());
            objCliente.setCnpj(cnpjTXT.getText());
            objCliente.setCpf(cpfTXT.getText());
            objCliente.setTelefone(telefoneTXT.getText());
            
            ClienteDAO objClienteDAO = new ClienteDAO();
            objClienteDAO.alterarCliente(objCliente);
            
                    
        }
        private void deletarCliente() {
            int id;
            try {
                 id = Integer.parseInt(codigoTXT.getText());
            Cliente objCliente = new Cliente();
            objCliente.setCodigo(id);
            
            ClienteDAO objClienteDAO = new ClienteDAO();
            objClienteDAO.deletarCliente(objCliente);
            } catch (SQLException e) {
                JOptionPane.showConfirmDialog(null, "Erro ao deletar\n"+e);
            } 
        }
         
        private void listarClientes() {
        
            DefaultTableModel modelo = (DefaultTableModel) tabelaCliente.getModel();
            List<Cliente> clientesLista = new ArrayList<>();
            modelo.setNumRows(0); 

            try {
            clientesLista = objClienteDAO.listarTodos();


            for(Cliente objCliente : clientesLista) {
                modelo.addRow(new Object[]{
                    objCliente.getCodigo(),
                    objCliente.getNome(),
                    objCliente.getDocumento(),
                    objCliente.getEmail(),
                    objCliente.getTelefone(),

                });
            }}catch(SQLException e) {
                e.printStackTrace();
            }
    }
        private void salvar(){
            Cliente objCliente = new Cliente();
        objCliente.setNome(nomeTXT.getText());
        objCliente.setEndereco(enderecoTXT.getText());
        objCliente.setTelefone(telefoneTXT.getText());
        objCliente.setCnpj(cnpjTXT.getText());
        objCliente.setCpf(cpfTXT.getText());
        objCliente.setEmail(emailTXT.getText());
        
        ClienteDAO objClienteDAO = new ClienteDAO();
        objClienteDAO.salvar(objCliente);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarBT;
    private javax.swing.JButton atualizarBT;
    private javax.swing.JButton carregarBt1;
    private javax.swing.JTextField cnpjTXT;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JTextField cpfTXT;
    private javax.swing.JButton deletarBT;
    private javax.swing.JTextField emailTXT;
    private javax.swing.JTextField enderecoTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparBT;
    private javax.swing.JTextField nomeTXT;
    private javax.swing.JButton sairBT1;
    private javax.swing.JButton salvarBT;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField telefoneTXT;
    // End of variables declaration//GEN-END:variables
}
