/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.LivroDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Editora;
import model.Livro;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Rodrigo
 */
public class LivroTela extends javax.swing.JFrame {
    LivroDAO objLivroDAO = new LivroDAO();
    /**
     * Creates new form LivroTela
     */
    public LivroTela() {
        initComponents();
        listarDados();
    }
     private void listarDados (){
        try {
            DefaultTableModel model = (DefaultTableModel)tabelaLivro.getModel();
            model.setNumRows(0);
            
            List<Livro> livroLista = objLivroDAO.ListarDados();
            for (int i = 0; i < livroLista.size(); i++) {
                model.addRow(new Object[]{
                   livroLista.get(i).getISBN(),
                   livroLista.get(i).getNomeLivro(),
                   livroLista.get(i).getAutor(),
                   livroLista.get(i).getAssunto(),
                   livroLista.get(i).getEditora_codigo().getNome(),
                   livroLista.get(i).getQuantidade()
                });
                  
            }
        } catch (SQLException erro) {
            JOptionPane.showConfirmDialog(null, "Erro ao listar"+erro);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carregarBt1 = new javax.swing.JButton();
        deletarBT = new javax.swing.JButton();
        atualizarBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLivro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeTXT = new javax.swing.JTextField();
        autorTXT = new javax.swing.JTextField();
        isbnTXT = new javax.swing.JTextField();
        salvarBT = new javax.swing.JButton();
        assuntoTXT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        limparBT = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        editoraTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantidadeTXT = new javax.swing.JTextField();
        sairBT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        carregarBt1.setBackground(new java.awt.Color(0, 204, 204));
        carregarBt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        carregarBt1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\carregar.png")); // NOI18N
        carregarBt1.setText("Carregar");
        carregarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarBt1ActionPerformed(evt);
            }
        });

        deletarBT.setBackground(new java.awt.Color(0, 204, 204));
        deletarBT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deletarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\deletar.png")); // NOI18N
        deletarBT.setText("Deletar");
        deletarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBTActionPerformed(evt);
            }
        });

        atualizarBT.setBackground(new java.awt.Color(0, 204, 204));
        atualizarBT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        atualizarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\atualizar.png")); // NOI18N
        atualizarBT.setText("Atualizar");
        atualizarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBTActionPerformed(evt);
            }
        });

        tabelaLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Nome", "Autor", "Assunto", "Editora", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaLivro);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\livro_icone (1).png")); // NOI18N
        jLabel1.setText("Livros");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Atributos Livros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel2.setText("Nome");

        jLabel3.setText("Autor");

        jLabel4.setText("ISBN");

        salvarBT.setBackground(new java.awt.Color(0, 204, 204));
        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        jLabel5.setText("Assunto");

        limparBT.setBackground(new java.awt.Color(0, 204, 204));
        limparBT.setText("Limpar");
        limparBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBTActionPerformed(evt);
            }
        });

        jLabel7.setText("Editora");

        jLabel6.setText("Quantidade");

        quantidadeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(isbnTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(editoraTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(quantidadeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(113, 113, 113)
                                    .addComponent(salvarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(limparBT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(nomeTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                                .addComponent(autorTXT)
                                .addComponent(assuntoTXT)))))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isbnTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(editoraTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(autorTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assuntoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(limparBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(quantidadeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sairBT1.setBackground(new java.awt.Color(0, 204, 204));
        sairBT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sairBT1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\sair.png")); // NOI18N
        sairBT1.setText("Sair");
        sairBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atualizarBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carregarBt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deletarBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairBT1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel1)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atualizarBT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(carregarBt1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(deletarBT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(sairBT1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carregarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarBt1ActionPerformed
        // TODO add your handling code here:
        try {
            CarregarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Clique em um Registro Primeiro\n"+e);
        }
        
    }//GEN-LAST:event_carregarBt1ActionPerformed

    private void deletarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBTActionPerformed
        // TODO add your handling code here:
        try {
            ExcluirDados();
        listarDados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Clique em um Registro Primeiro\n"+e);
        }
        
    }//GEN-LAST:event_deletarBTActionPerformed

    private void atualizarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBTActionPerformed
        // TODO add your handling code here:
        listarDados();
    }//GEN-LAST:event_atualizarBTActionPerformed

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        // TODO add your handling code here:
        try {
            salvar();
            listarDados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Os campos NAO podem retornar Vazios\n"+e);
        }
        
    }//GEN-LAST:event_salvarBTActionPerformed

    private void sairBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBT1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairBT1ActionPerformed

    private void limparBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBTActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_limparBTActionPerformed

    private void quantidadeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LivroTela().setVisible(true);
            }
        });
    }

    private void limparCampos(){
    isbnTXT.setText("");
    nomeTXT.setText("");
    autorTXT.setText("");
    editoraTXT.setText("");
    assuntoTXT.setText("");
    }
    
    private void CarregarCampos() {
         int setar = tabelaLivro.getSelectedRow();
         isbnTXT.setText(tabelaLivro.getModel().getValueAt(setar, 0).toString());
         nomeTXT.setText(tabelaLivro.getModel().getValueAt(setar, 1).toString());
         autorTXT.setText(tabelaLivro.getModel().getValueAt(setar, 2).toString());
         assuntoTXT.setText(tabelaLivro.getModel().getValueAt(setar, 3).toString());
         editoraTXT.setText(tabelaLivro.getModel().getValueAt(setar, 4).toString());
     }
    
    private void AlterarCampos () {
        try {
             Livro objLivro = new Livro();
        objLivro.setISBN(Integer.parseInt(isbnTXT.getText()));
        objLivro.setNomeLivro(nomeTXT.getText());
        objLivro.setAutor(autorTXT.getText());
        objLivro.setAssunto(assuntoTXT.getText());
        objLivro.setEditora_codigo(new Editora (Integer.parseInt(editoraTXT.getText())));
            // instanciando a classe UsuarioDAO do pacote dao e criando seu objeto dao
           objLivroDAO.alterar(objLivro);
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null,"Erro ao Alterar\n"+e);
        }
       
    }
    private void ExcluirDados (){
        try {
                Livro objLivro = new Livro();
                objLivro.setISBN(Integer.parseInt(isbnTXT.getText()));
    
                objLivroDAO.deletar(objLivro);
        } catch (SQLException e) {
            JOptionPane.showConfirmDialog(null,"Erro ao Deletar\n"+e);
        }
       
        
    }
    private void salvar(){
        Livro objLivro = new Livro();
        objLivro.setISBN(Integer.parseInt(isbnTXT.getText()));
        objLivro.setEditora_codigo(new Editora (Integer.parseInt(editoraTXT.getText())));
        objLivro.setNomeLivro(nomeTXT.getText());
        objLivro.setAutor(autorTXT.getText());
        objLivro.setAssunto(assuntoTXT.getText());
        objLivro.setQuantidade(Integer.parseInt(quantidadeTXT.getText()));
        
        LivroDAO livroDAO = new LivroDAO();
        livroDAO.salvarLivro(objLivro);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assuntoTXT;
    private javax.swing.JButton atualizarBT;
    private javax.swing.JTextField autorTXT;
    private javax.swing.JButton carregarBt1;
    private javax.swing.JButton deletarBT;
    private javax.swing.JTextField editoraTXT;
    private javax.swing.JTextField isbnTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparBT;
    private javax.swing.JTextField nomeTXT;
    private javax.swing.JTextField quantidadeTXT;
    private javax.swing.JButton sairBT1;
    private javax.swing.JButton salvarBT;
    private javax.swing.JTable tabelaLivro;
    // End of variables declaration//GEN-END:variables
}
