/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import dao.ClienteDAO;
import dao.EditoraDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Editora;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class EditoraTela extends javax.swing.JFrame {

    /**
     * Creates new form EditoraTela
     */
    public EditoraTela() {
        initComponents();
        listarDados();
    }
     private void listarDados (){
        try {
           EditoraDAO objEditoraDAO = new EditoraDAO();
            DefaultTableModel model = (DefaultTableModel)tabelaEditoras.getModel();
            model.setNumRows(0);
            
            List<Editora> editoraLista = objEditoraDAO.listarTodos();
            for (int i = 0; i < editoraLista.size(); i++) {
                model.addRow(new Object[]{
                   editoraLista.get(i).getCodigo(),
                   editoraLista.get(i).getNome(),
                   editoraLista.get(i).getTelefone(),
                   editoraLista.get(i).getNome_gerente(),
                   editoraLista.get(i).getEndereco()
                });
                  
            }
        } catch (SQLException erro) {
            JOptionPane.showConfirmDialog(null, "Erro ao listar\n"+erro);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterarBT = new javax.swing.JButton();
        carregarBt1 = new javax.swing.JButton();
        deletarBT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEditoras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomeTXT = new javax.swing.JTextField();
        enderecoTXT = new javax.swing.JTextField();
        telefoneTXT = new javax.swing.JTextField();
        salvarBT = new javax.swing.JButton();
        gerenteTXT = new javax.swing.JTextField();
        limparBT = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        codigoTXT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sairBT1 = new javax.swing.JButton();
        atualizarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        alterarBT.setBackground(new java.awt.Color(0, 204, 204));
        alterarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\alterar.png")); // NOI18N
        alterarBT.setText("Alterar");
        alterarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarBTActionPerformed(evt);
            }
        });

        carregarBt1.setBackground(new java.awt.Color(0, 204, 204));
        carregarBt1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\carregar.png")); // NOI18N
        carregarBt1.setText("Carregar");
        carregarBt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarBt1ActionPerformed(evt);
            }
        });

        deletarBT.setBackground(new java.awt.Color(0, 204, 204));
        deletarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\deletar.png")); // NOI18N
        deletarBT.setText("Deletar");
        deletarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBTActionPerformed(evt);
            }
        });

        tabelaEditoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Telefone", "Gerente", "Endereço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaEditoras);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\993891 (1).png")); // NOI18N
        jLabel1.setText("Editoras");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel2.setText("Nome");

        jLabel3.setText("Endereço");

        jLabel4.setText("Telefone");

        salvarBT.setBackground(new java.awt.Color(0, 204, 204));
        salvarBT.setText("Salvar");
        salvarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBTActionPerformed(evt);
            }
        });

        limparBT.setBackground(new java.awt.Color(0, 204, 204));
        limparBT.setText("Limpar");
        limparBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBTActionPerformed(evt);
            }
        });

        jLabel6.setText("Código");

        codigoTXT.setEnabled(false);

        jLabel7.setText("Gerente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(telefoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(salvarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(limparBT, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(gerenteTXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTXT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(enderecoTXT, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(357, 357, 357))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(codigoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(enderecoTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gerenteTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salvarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limparBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(telefoneTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        sairBT1.setBackground(new java.awt.Color(0, 204, 204));
        sairBT1.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\sair.png")); // NOI18N
        sairBT1.setText("Sair");
        sairBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBT1ActionPerformed(evt);
            }
        });

        atualizarBT.setBackground(new java.awt.Color(0, 204, 204));
        atualizarBT.setIcon(new javax.swing.ImageIcon("C:\\Users\\rodri\\Downloads\\iloveimg-resized\\atualizar.png")); // NOI18N
        atualizarBT.setText("Atualizar");
        atualizarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(299, 299, 299))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(atualizarBT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carregarBt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alterarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deletarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sairBT1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alterarBT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(carregarBt1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(deletarBT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(sairBT1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(atualizarBT, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alterarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarBTActionPerformed
        // TODO add your handling code here:
        try {
            alterarCampos();
            listarDados();
            limparCampos();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Carregue um Registro Primeiro\n"+e);
        }
        
    }//GEN-LAST:event_alterarBTActionPerformed

    private void carregarBt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarBt1ActionPerformed
        // TODO add your handling code here:
        try {
            CarregarCampos();
            listarDados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Clique em um Registro Primeiro\n"+e);
        }
        
    }//GEN-LAST:event_carregarBt1ActionPerformed

    private void deletarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBTActionPerformed
        // TODO add your handling code here:
        try {
            ExcluirDados();
            listarDados();
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Carregue um Registro Primeiro\n"+e);
        }
        
    }//GEN-LAST:event_deletarBTActionPerformed

    private void salvarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBTActionPerformed
        // TODO add your handling code here:
        try {
            salvar();
            limparCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Os campos NAO podem retornar Vazios\n"+e);
        }
        
    }//GEN-LAST:event_salvarBTActionPerformed

    private void sairBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBT1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_sairBT1ActionPerformed

    private void atualizarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBTActionPerformed
        // TODO add your handling code here:
        listarDados();
    }//GEN-LAST:event_atualizarBTActionPerformed

    private void limparBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBTActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_limparBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditoraTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditoraTela().setVisible(true);
            }
        });
    }
    private void CarregarCampos() {
         int setar = tabelaEditoras.getSelectedRow();
         codigoTXT.setText(tabelaEditoras.getModel().getValueAt(setar, 0).toString());
         nomeTXT.setText(tabelaEditoras.getModel().getValueAt(setar, 1).toString());
         telefoneTXT.setText(tabelaEditoras.getModel().getValueAt(setar, 2).toString());
         gerenteTXT.setText(tabelaEditoras.getModel().getValueAt(setar, 3).toString());
         enderecoTXT.setText(tabelaEditoras.getModel().getValueAt(setar, 4).toString());   
     }
    
     private void ExcluirDados (){
        int id;
        
         try {
             id = Integer.parseInt(codigoTXT.getText());
            Editora objEditora = new Editora();
            objEditora.setCodigo(id);

            EditoraDAO objEditoraDAO = new EditoraDAO();
            objEditoraDAO.deletar(objEditora);
         } catch (SQLException e) {
             JOptionPane.showConfirmDialog(null, "Erro ao deletar\n"+e);
         }
    }
     
     private void alterarCampos() {
         int id;
         id = Integer.parseInt(codigoTXT.getText());
         Editora objEditora = new Editora();
         objEditora.setCodigo(id);
         objEditora.setNome(nomeTXT.getText());
         objEditora.setTelefone(telefoneTXT.getText());
         objEditora.setNome_gerente(gerenteTXT.getText());
         objEditora.setEndereco(enderecoTXT.getText());
         EditoraDAO objEditoraDAO = new EditoraDAO();
         objEditoraDAO.alterar(objEditora);   
     }
     private void limparCampos(){
         codigoTXT.setText("");
         nomeTXT.setText("");
         enderecoTXT.setText("");
         gerenteTXT.setText("");
         telefoneTXT.setText("");
     }
     private void salvar(){
         Editora objEditora = new Editora();
        objEditora.setNome(nomeTXT.getText());
        objEditora.setEndereco(enderecoTXT.getText());
        objEditora.setNome_gerente(gerenteTXT.getText());
        objEditora.setTelefone(telefoneTXT.getText());
        
        EditoraDAO objEditoraDAO = new EditoraDAO();
        objEditoraDAO.salvarEditora(objEditora);
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarBT;
    private javax.swing.JButton atualizarBT;
    private javax.swing.JButton carregarBt1;
    private javax.swing.JTextField codigoTXT;
    private javax.swing.JButton deletarBT;
    private javax.swing.JTextField enderecoTXT;
    private javax.swing.JTextField gerenteTXT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limparBT;
    private javax.swing.JTextField nomeTXT;
    private javax.swing.JButton sairBT1;
    private javax.swing.JButton salvarBT;
    private javax.swing.JTable tabelaEditoras;
    private javax.swing.JTextField telefoneTXT;
    // End of variables declaration//GEN-END:variables
}
